Repository asuc-octo/berkeley-mobile-ios, pull requests merged in 2025-05, with the labels that each got.

#359 BER-64: Implement Swift Concurrency Firebase APIs In ResourcesViewModel
  berkeley-mobile/Resources/ResourcesView.swift
  berkeley-mobile/Resources/ResourcesViewModel.swift
Labels: refactor

#368 BER-81: Rewrite/Recreate EventTableViewCell in SwiftUI
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Common/BMCachedAsyncImageView.swift
  berkeley-mobile/Common/EventTableViewCell.swift
  berkeley-mobile/Events/Academic/AcademicEventRowView.swift
  berkeley-mobile/Events/Calendar/CalendarTablePairView.swift
  berkeley-mobile/Utils/View+Extension.swift
Labels: UI

#371 BER-106: Rewrite EventManager.shared.addEventToCalendar using Async & iOS 17 API
  berkeley-mobile/Data/EventManager.swift
  berkeley-mobile/Data/ItemProtocols/CalendarEvent.swift
  berkeley-mobile/Events/Academic/AcademicCalendarViewModel.swift
Labels: enhancement

#375 BER-110: Use iOS 17.0+ Map API in SafetyLogDetailView
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Safety/BMSafetyMapMarker.swift
  berkeley-mobile/Safety/SafetyLogDetailView.swift
  berkeley-mobile/Safety/SafetyMapView.swift
  berkeley-mobile/Safety/SafetyView.swift
  berkeley-mobile/Safety/SafetyViewModel.swift
Labels: UI
