Repository asuc-octo/berkeley-mobile-ios, pull requests merged in 2025-03, with the labels that each got.

#337 BER-76: Resolve BER-10 GoogleService-Info.plist Issue + Gym Scrappers
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Fitness/Fitness+Controllers/GymClassesController.swift
  berkeley-mobile/Fitness/FitnessViewController.swift
  berkeley-mobile/Fitness/GymDetailViewController.swift
  berkeley-mobile/Fitness/GymOccupancyScrapper.swift
  berkeley-mobile/Fitness/GymOccupancyView.swift
  berkeley-mobile/Fitness/GymOccupancyViewModel.swift
Labels: bug

#335 BER-74: Replace SegmentedControlViewController with SegmentedControlView in Events Tab
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Calendar/Academic/AcademicCalendarViewController.swift
  berkeley-mobile/Calendar/CalendarViewController.swift
  berkeley-mobile/Calendar/Campus/CampusCalendarViewController.swift
  berkeley-mobile/Calendar/EventsView.swift
  berkeley-mobile/Common/BMTopBlobView.swift
  berkeley-mobile/Resources/ResourcesView.swift
  berkeley-mobile/Tab Bar/TabBarController.swift
Labels: UI

#342 BER-60: New Safety View Maps UI with Custom Annotations
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Assets/Colors/Colors.swift
  berkeley-mobile/Constants.swift
  berkeley-mobile/Map/MapMarkersDropdownView.swift
  berkeley-mobile/Map/MapUserLocationButton.swift
  berkeley-mobile/Map/MapViewController.swift
  berkeley-mobile/Safety/BMDrawerView.swift
  berkeley-mobile/Safety/SafetyLogDetailView.swift
  berkeley-mobile/Safety/SafetyMapView.swift
  berkeley-mobile/Safety/SafetyView.swift
  berkeley-mobile/Safety/SafetyViewModel.swift
  berkeley-mobile/Utils/View+Extension.swift
Labels: enhancement, UI

#350 BER-88: Temporary Fix Crash Originating From Filter.apply(filters:on:indices:completion:)
  berkeley-mobile/Common/FilterTableView/FilterTableView.swift
  berkeley-mobile/Common/FilterView/Filter.swift
  berkeley-mobile/Dining/DiningMenuViewController.swift
  berkeley-mobile/Dining/DiningViewController.swift
  berkeley-mobile/Fitness/FitnessViewController.swift
  berkeley-mobile/Libraries/StudyViewController.swift
Labels: bug

#347 BER-70: Rewrite Home Search View
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Assets/Colors/Colors.swift
  berkeley-mobile/Data/ItemProtocols/HasLocation.swift
  berkeley-mobile/MainContainerViewController.swift
  berkeley-mobile/Map/BMContentUnavailableView.swift
  berkeley-mobile/Map/MapMarkerDetailView.swift
  berkeley-mobile/Map/MapViewController.swift
  berkeley-mobile/Map/SearchBarView.swift
  berkeley-mobile/Map/SearchResultCell.swift
  berkeley-mobile/Map/SearchResultsListRowView.swift
  berkeley-mobile/Map/SearchResultsView.swift
  berkeley-mobile/Map/SearchViewModel.swift
  berkeley-mobile/Utils/CLLocation+Extension.swift
  berkeley-mobile/Utils/NSCoding+Extension.swift
  berkeley-mobile/Utils/View+Extension.swift
Labels: enhancement, UI
