Repository asuc-octo/berkeley-mobile-ios, pull requests merged in 2025-04, with the labels that each got.

#353 BER-90: Fix Incorrect BMCalendarView Calendar Dates
  berkeley-mobile/Events/Calendar/BMCalendarView.swift
  berkeley-mobile/Utils/Date+Extension.swift
Labels: bug

#352 BER-84: Fix Gym Occupancy Unnecessary Refresh Upon Switch
  berkeley-mobile/Fitness/FitnessViewController.swift
  berkeley-mobile/Fitness/GymOccupancyView.swift
  berkeley-mobile/Fitness/GymOccupancyViewModel.swift
  berkeley-mobile/HomeView.swift
Labels: enhancement

#346 BER-87: Rewrite CampusEventTableViewCell
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Common/FilterTableView/HomeSectionListRowView.swift
  berkeley-mobile/Constants.swift
  berkeley-mobile/Data/ItemProtocols/HasImage.swift
  berkeley-mobile/Events/Campus/CampusCalendarViewController.swift
  berkeley-mobile/Events/Campus/CampusEventRowView.swift
Labels: enhancement, UI

#343 BER-73: Rewrite OpenTimesCardView in SwiftUI
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Common/DetailView/OpenTimesCardSwiftUIView.swift
  berkeley-mobile/Utils/DayOfWeek.swift
  berkeley-mobile/Utils/View+Extension.swift
Labels: enhancement, UI

#351 BER-89: Fix Incorrect StateObject Configuration For HomeViewModel
  berkeley-mobile/HomeView.swift
  berkeley-mobile/MainContainerViewController.swift
Labels: bug

#345 BER-66: Update Home Map User Location Button Based On Location Permissions
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/AppDelegate.swift
  berkeley-mobile/Common/DetailView/LocationDetailView.swift
  berkeley-mobile/Data/BMLocationManager.swift
  berkeley-mobile/Data/LocationManager.swift
  berkeley-mobile/Dining/DiningViewController.swift
  berkeley-mobile/Fitness/FitnessViewController.swift
  berkeley-mobile/Libraries/StudyViewController.swift
  berkeley-mobile/Map/MapUserLocationButton.swift
  berkeley-mobile/Map/MapViewController.swift
  berkeley-mobile/Map/SearchResultCell.swift
  berkeley-mobile/Utils/CLLocation+Extension.swift
Labels: enhancement, UI

#357 BER-96: Recreate ActionButton in SwiftUI
  berkeley-mobile.xcodeproj/project.pbxproj
  berkeley-mobile/Common/BMActionButton.swift
Labels: UI

#358 BER-101: SafetyLogDetailView Selected Map Annotation Change Tabs Bug
  berkeley-mobile/Safety/SafetyLogDetailView.swift
  berkeley-mobile/Safety/SafetyView.swift
Labels: bug

#360 BER-99: Fix Resources Section Header Text and Title Alignment
  berkeley-mobile/Resources/ResourcesSectionDropdown.swift
  berkeley-mobile/Resources/ResourcesView.swift
Labels: enhancement, refactor
